### ISSUE TITLE
macOS version results in '“Pdf Metadata Editor” is damaged and can’t be opened'

### ISSUE THREAD

**Issue by vagari** [zaro/pdf-metadata-editor#25]
Hello, I've tried both versions of the Mac download, and also the previous version (3.0.1) and all of them result in the following error message from the system. I've done some basic troubleshooting. But so far just keep getting the same message. And I didn't see another issue mentioning that.

> “Pdf Metadata Editor” is damaged and can’t be opened. You should move it to the Trash.

I imagine it has something to do with how the app is generated. I'm on a fairly new, M2 16" MacBook Pro and on the latest OS, 14.4.1. Thanks!

**Comment by zaro** [comment]
Hello,

Yes I am aware it this. This is not really a problem with the program! It just that Apple doesn't alow anymore unsigned binaries by default. I don't even own a Mac anymore an d I am not really interested in paying Apple so that people can use a tool that is largely free.

If you want a workaround I think this articles show some:

https://github.molgen.mpg.de/pages/bs/macOSnotes/mac/mac_procs_unsigned.html

https://www.madcaped.com/2021/02/run-execute-not-signed-and-notarized.html?m=1


Cheers,
Zaro


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jake Harvey ***@***.***>
Sent: Sunday, April 14, 2024 5:17:49 AM
To: zaro/pdf-metadata-editor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zaro/pdf-metadata-editor] macOS version results in '“Pdf Metadata Editor” is damaged and can’t be opened' (Issue #25)


Hello, I've tried both versions of the Mac download, and also the previous version (3.0.1) and all of them result in the following error message from the system. I've done some basic troubleshooting. But so far just keep getting the same message. And I didn't see another issue mentioning that.

“Pdf Metadata Editor” is damaged and can’t be opened. You should move it to the Trash.

I imagine it has something to do with how the app is generated. I'm on a fairly new, M2 16" MacBook Pro and on the latest OS, 14.4.1. Thanks!

**Comment by vagari** [comment]
Thanks for the explanation. Can't fault you for that. Sadly when I tried those solutions, I get prompted for authentication... but nothing changes. I'd be curious if it works for anyone else. The newer System Settings even has some differences with what's described.

**Comment by vagari** [comment]
I'm not 100% sure, but I ended up trying this other reference to "clearing attributes." 

https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

Using `sudo`  I got an error that then required adding, and toggling on, my terminal app (iTerm) in the "App Management" security pane. After that I ran the `xattr` command again, got no error, and the app gave me the old, "are you sure you want to open this" style pop up when I right clicked and selected open. The app then started and looks to be working.

Hopefully that helps someone in the future. Though as mentioned I'm not positive which part officially got things working.
