### ISSUE TITLE
Exception when opening a file modified in Calibre

### ISSUE THREAD

**Issue by canpolat** [zaro/pdf-metadata-editor#4]
Hi,

Calibre has a function to embed metadata into PDF files. I have a couple of files that went through that process. When I try to open them in your editor, I get the following error message:

> Error while opening file:
> org.apache.xmpbox.xml.XmpParsingException: Cannot find a definition for the namespace http://calibre-ebook.com/xmp-namespace

This is clearly an exception coming from the xmpbox library. But I believe, you could handle this exception and offer the user to remove all metadata related to Calibre namespace (keeping the actual XMP data).

Is this something you would like to improve on?

**Comment by zaro** [comment]
Yeah, I know about this issue.
I have opened issue with pdfbox https://issues.apache.org/jira/browse/PDFBOX-3440 .
But it seems it's a design limitation in the 2.0 version, so I reverted to using 1.8.12 which doesn't have this problem.
So this is fixed in 2.0.2, but I will leave the issue open for now.

**Comment by canpolat** [comment]
Hi, thanks for the quick response. I hope the pdfbox team fixes it soon.
